// CMP Provider detection rules
const cmpProviders = {
    "OneTrust": () => !!window.OneTrust || document.querySelector("script[src*='onetrust.com']"),
    "InMobi": () => document.querySelector("script[src*='inmobi.com']"),
    "Sourcepoint": () => document.querySelector("script[src*='sourcepoint.com']"),
    "TrustArc": () => document.querySelector("script[src*='trustarc.com']"),
    "Admiral": () => document.querySelector("script[src*='admiral.com']"),
    "Transcend": () => document.querySelector("script[src*='transcend.io']"),
    "Osano": () => document.querySelector("script[src*='cmp.osano.com']"),
    "Cookiebot": () => !!window.CookieConsent || document.querySelector("script[src*='cookiebot.com']"),
    "CookieYes": () => document.querySelector("script[src*='cookieyes.com']"),
    "TrustCassie": () => document.querySelector("script[src*='trustcassie.com']"),
    "Termly": () => document.querySelector("script[src*='termly.io']"),
    "Ketch": () => document.querySelector("script[src*='ketch.com']"),
    "CookieScript": () => document.querySelector("script[src*='cookie-script.com']"),
    "Nextroll": () => document.querySelector("script[src*='nextroll.com']"),
    "Quantcast": () => !!window.quantserve || document.querySelector("script[src*='quantserve.com']") || document.querySelector(".qc-cmp2-container"),
    "Didomi": () => !!window.Didomi || document.querySelector("script[src*='didomi.io']") || document.querySelector("#didomi-host"),
    "Usercentrics": () => !!window.usercentrics || document.querySelector("script[src*='usercentrics.eu']") || document.querySelector("#usercentrics-root"),
    "Evidon": () => !!window.evidon || document.querySelector("script[src*='evidon.com']"),
    "LiveRamp": () => document.querySelector("script[src*='liveramp.com']"),
    "Crownpeak": () => document.querySelector("script[src*='crownpeak.com']") || document.querySelector("#cmpbox"),
    "Securiti": () => document.querySelector("script[src*='securiti.ai']"),
    "CivicUK": () => document.querySelector("script[src*='civicuk.com']") || document.querySelector("#CookieControl"),
    "iubenda": () => document.querySelector("script[src*='iubenda.com']") || document.querySelector("#iubenda-cs-banner"),
    "Complianz": () => document.querySelector("script[src*='complianz']") || document.querySelector("#cmplz-cookiebanner-container"),
    "CookieInformation": () => document.querySelector("script[src*='cookie-information.com']"),
    "CookieFirst": () => document.querySelector("script[src*='cookie-first.com']"),
    "Tealium": () => !!window.utag || document.querySelector("script[src*='tealium.com']"),
    "Ensighten": () => !!window.ensighten || document.querySelector("script[src*='ensighten.com']"),
    "Axeptio": () => !!window.axeptio || document.querySelector("script[src*='axept.io']"),
    "Klaro": () => !!window.klaro || document.querySelector("script[src*='kiprotect.com']"),
    "PrimeData": () => document.querySelector("script[src*='primedata.ai']"),
    "Piwik": () => document.querySelector("script[src*='piwik.pro']"),
    "Commanders Act": () => document.querySelector("script[src*='commandersact.com']"),
    "Onetag": () => document.querySelector("script[src*='onetag-sys.com']"),
    "Opencmp": () => document.querySelector("script[src*='opencmp.net']"),
    "Ogury": () => document.querySelector("script[src*='ogury.co']"),
    "Chandago": () => document.querySelector("script[src*='chandago.com']"),
    "Sibbo": () => document.querySelector("script[src*='sibbo.net']"),
    "Tapad": () => document.querySelector("script[src*='tapad.com']")
};

// Cookie pattern detection rules
const cookiePatterns = {
    "euconsent-v2": "IAB TCF 2.0",
    "didomi_*": "Didomi",
    "consentUUID": "OneTrust",
    "sp_*": "Sourcepoint",
    "iab_consent": "IAB Framework",
    "cookie_consent": "Generic Consent Storage",
    "cookieyes-consent": "CookieYes",
    "cc_cookie": "Civic Cookie Control",
    "piwik_optin": "Piwik PRO",
    "quantcast_choice": "Quantcast Choice",
    "admiral_consent": "Admiral",
    "transcend_consent": "Transcend",
    "ketch_consent": "Ketch",
    "cookie_script": "CookieScript",
    "nextroll_consent": "Nextroll",
    "axeptio_cookies": "Axeptio",
    "klaro": "Klaro",
    "cmplz_": "Complianz",
    "complianz_": "Complianz",
    "usercentrics": "Usercentrics",
    "evidon": "Evidon",
    "CookieConsent_": "CookieInformation",
    "cookie-first": "CookieFirst",
    "tealium": "Tealium",
    "ensighten": "Ensighten",
    "_iub": "iubenda",
    "sibbo_": "Sibbo",
    "tapad_": "Tapad",
    "ogury_": "Ogury",
    "chandago_": "Chandago",
    "opencmp_": "Opencmp"
};

module.exports = {
    cmpProviders,
    cookiePatterns
};
