services:
  - type: web
    name: cmp-detector
    env: node
    buildCommand: |
      mkdir -p /opt/render/.cache/puppeteer
      apt-get update
      apt-get install -y \
        ca-certificates \
        fonts-liberation \
        libasound2 \
        libgbm1 \
        libnspr4 \
        libnss3 \
        libxss1
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
    plan: free