services:
  - type: web
    name: cmp-detector
    env: node
    buildCommand: |
      npx playwright install chromium --with-deps
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free