services:
  - type: web
    name: cmp-detector
    env: node
    buildCommand: |
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y \
        google-chrome-stable \
        ca-certificates \
        fonts-liberation \
        libasound2 \
        libgbm1 \
        libnspr4 \
        libnss3 \
        libxss1
      which google-chrome-stable
      ls -l /usr/bin/google-chrome*
      google-chrome-stable --version || true
      npm install
    startCommand: |
      which google-chrome-stable
      ls -l /usr/bin/google-chrome*
      google-chrome-stable --version || true
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    plan: free