services:
  - type: web
    name: cmp-detector
    env: node
    buildCommand: |
      # Make install script executable
      mkdir -p scripts
      cat > scripts/install-chrome.sh << 'EOF'
      #!/bin/bash
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable
      EOF
      chmod +x scripts/install-chrome.sh

      # Install Chrome and its dependencies
      ./scripts/install-chrome.sh

      # Install dependencies for Chrome
      apt-get install -y \
        ca-certificates \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libatspi2.0-0 \
        libcups2 \
        libdbus-1-3 \
        libdrm2 \
        libgbm1 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libxcomposite1 \
        libxdamage1 \
        libxfixes3 \
        libxrandr2 \
        xdg-utils \
        libpangocairo-1.0-0 \
        libpango-1.0-0 \
        libcairo2 \
        libatspi2.0-0 \
        libgtk2.0-0

      # Create Puppeteer cache directory
      mkdir -p /opt/render/.cache/puppeteer

      # Install Node dependencies
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    plan: free