services:
  - type: web
    name: cmp-detector
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free