services:
  - type: web
    name: cmp-scanner
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: 3000