services:
  - type: web
    name: cmp-detector
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install
    startCommand: |
      echo "Chromium version:" && \
      chromium --version && \
      echo "Chromium location:" && \
      which chromium && \
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
    plan: free