services:
  - type: web
    name: cmp-detector
    env: node
    buildCommand: |
      mkdir -p /home/render/.cache/puppeteer
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /home/render/.cache/puppeteer
    plan: free