services:
  - type: web
    name: cmp-scanner
    env: node
    plan: free
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: 3000
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"